// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Achievements {
    public const string achievement_impossible_brush = "CgkIje3UzOYaEAIQDw"; // <GPGSID>
    public const string achievement_palette_novice = "CgkIje3UzOYaEAIQEQ"; // <GPGSID>
    public const string achievement_impossible_bucket = "CgkIje3UzOYaEAIQEA"; // <GPGSID>
    public const string achievement_normal_pencil = "CgkIje3UzOYaEAIQCA"; // <GPGSID>
    public const string achievement_its_cyan_not_blue = "CgkIje3UzOYaEAIQFA"; // <GPGSID>
    public const string achievement_its_blue_not_cyan = "CgkIje3UzOYaEAIQFQ"; // <GPGSID>
    public const string achievement_thanks_fisheryates = "CgkIje3UzOYaEAIQBQ"; // <GPGSID>
    public const string achievement_palette_adept = "CgkIje3UzOYaEAIQEg"; // <GPGSID>
    public const string achievement_normal_brush = "CgkIje3UzOYaEAIQCQ"; // <GPGSID>
    public const string leaderboard_impossible_mode = "CgkIje3UzOYaEAIQGA"; // <GPGSID>
    public const string achievement_hard_pencil = "CgkIje3UzOYaEAIQCw"; // <GPGSID>
    public const string leaderboard_normal_mode = "CgkIje3UzOYaEAIQFg"; // <GPGSID>
    public const string achievement_impossible_pencil = "CgkIje3UzOYaEAIQDg"; // <GPGSID>
    public const string achievement_normal_bucket = "CgkIje3UzOYaEAIQCg"; // <GPGSID>
    public const string achievement_your_reward_more_questions = "CgkIje3UzOYaEAIQBg"; // <GPGSID>
    public const string achievement_palette_master = "CgkIje3UzOYaEAIQEw"; // <GPGSID>
    public const string leaderboard_hard_mode = "CgkIje3UzOYaEAIQFw"; // <GPGSID>
    public const string achievement_hard_brush = "CgkIje3UzOYaEAIQDA"; // <GPGSID>
    public const string achievement_hard_bucket = "CgkIje3UzOYaEAIQDQ"; // <GPGSID>
    public const string achievement_participation_medal = "CgkIje3UzOYaEAIQAw"; // <GPGSID>
    public const string achievement_time_drops_in_decay = "CgkIje3UzOYaEAIQBA"; // <GPGSID>

    public const float UNLOCK = 100.0f;

    public const int BRONZE_SCORE = 40;
    public const int SILVER_SCORE = 80;
    public const int GOLD_SCORE = 120;
}

